image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - test

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""


checker:
    stage: test
    image:
        name: gitlab.cs.pub.ro:5050/compilatoare/tema-1-analiza-lexicala:latest
    script:
        - echo ""
